export const users = [
  {
    login: 'dersonsena',
    id: 9482515,
    node_id: 'MDQ6VXNlcjk0ODI1MTU=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/9482515?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/dersonsena',
    html_url: 'https://github.com/dersonsena',
    followers_url: 'https://api.github.com/users/dersonsena/followers',
    following_url:
      'https://api.github.com/users/dersonsena/following{/other_user}',
    gists_url: 'https://api.github.com/users/dersonsena/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/dersonsena/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/dersonsena/subscriptions',
    organizations_url: 'https://api.github.com/users/dersonsena/orgs',
    repos_url: 'https://api.github.com/users/dersonsena/repos',
    events_url: 'https://api.github.com/users/dersonsena/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/dersonsena/received_events',
    type: 'User',
    site_admin: false,
    name: 'Kilderson Sena',
    company: 'Yii Academy',
    blog: 'http://www.yiiacademy.com.br',
    location: 'Brasil',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 58,
    public_gists: 15,
    followers: 84,
    following: 42,
    created_at: '2014-10-31T14:12:30Z',
    updated_at: '2020-06-02T20:40:11Z',
  },
  {
    login: 'arthuralmeidap',
    id: 218371,
    node_id: 'MDQ6VXNlcjIxODM3MQ==',
    avatar_url: 'https://avatars1.githubusercontent.com/u/218371?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/arthuralmeidap',
    html_url: 'https://github.com/arthuralmeidap',
    followers_url: 'https://api.github.com/users/arthuralmeidap/followers',
    following_url:
      'https://api.github.com/users/arthuralmeidap/following{/other_user}',
    gists_url: 'https://api.github.com/users/arthuralmeidap/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/arthuralmeidap/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/arthuralmeidap/subscriptions',
    organizations_url: 'https://api.github.com/users/arthuralmeidap/orgs',
    repos_url: 'https://api.github.com/users/arthuralmeidap/repos',
    events_url: 'https://api.github.com/users/arthuralmeidap/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/arthuralmeidap/received_events',
    type: 'User',
    site_admin: false,
    name: 'Arthur Almeida',
    company: null,
    blog: 'http://arthuralmeidap.github.io',
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 27,
    public_gists: 8,
    followers: 34,
    following: 33,
    created_at: '2010-03-08T14:10:28Z',
    updated_at: '2020-05-29T12:47:25Z',
  },
  {
    login: 'AlyoshaS',
    id: 25611772,
    node_id: 'MDQ6VXNlcjI1NjExNzcy',
    avatar_url: 'https://avatars1.githubusercontent.com/u/25611772?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/AlyoshaS',
    html_url: 'https://github.com/AlyoshaS',
    followers_url: 'https://api.github.com/users/AlyoshaS/followers',
    following_url:
      'https://api.github.com/users/AlyoshaS/following{/other_user}',
    gists_url: 'https://api.github.com/users/AlyoshaS/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/AlyoshaS/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/AlyoshaS/subscriptions',
    organizations_url: 'https://api.github.com/users/AlyoshaS/orgs',
    repos_url: 'https://api.github.com/users/AlyoshaS/repos',
    events_url: 'https://api.github.com/users/AlyoshaS/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/AlyoshaS/received_events',
    type: 'User',
    site_admin: false,
    name: 'Evelyn Schmitz',
    company: '@TallerWebSolutions ',
    blog: '',
    location: 'Rio Grande do Sul, Brazil.',
    email: null,
    hireable: null,
    bio: 'Priestess of software.',
    twitter_username: null,
    public_repos: 45,
    public_gists: 47,
    followers: 125,
    following: 275,
    created_at: '2017-02-07T13:04:03Z',
    updated_at: '2020-06-01T17:11:38Z',
  },
  {
    login: 'lhguerra',
    id: 4529663,
    node_id: 'MDQ6VXNlcjQ1Mjk2NjM=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/4529663?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/lhguerra',
    html_url: 'https://github.com/lhguerra',
    followers_url: 'https://api.github.com/users/lhguerra/followers',
    following_url:
      'https://api.github.com/users/lhguerra/following{/other_user}',
    gists_url: 'https://api.github.com/users/lhguerra/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/lhguerra/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/lhguerra/subscriptions',
    organizations_url: 'https://api.github.com/users/lhguerra/orgs',
    repos_url: 'https://api.github.com/users/lhguerra/repos',
    events_url: 'https://api.github.com/users/lhguerra/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/lhguerra/received_events',
    type: 'User',
    site_admin: false,
    name: 'Luiz Henrique Guerra',
    company: '@TallerWebSolutions ',
    blog: 'https://twitter.com/guerrahluiz',
    location: 'Florianópolis, SC',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 29,
    public_gists: 6,
    followers: 28,
    following: 33,
    created_at: '2013-05-25T22:50:23Z',
    updated_at: '2020-05-28T20:50:47Z',
  },
  {
    login: 'guilhermedeoliveira',
    id: 20259146,
    node_id: 'MDQ6VXNlcjIwMjU5MTQ2',
    avatar_url: 'https://avatars0.githubusercontent.com/u/20259146?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/guilhermedeoliveira',
    html_url: 'https://github.com/guilhermedeoliveira',
    followers_url: 'https://api.github.com/users/guilhermedeoliveira/followers',
    following_url:
      'https://api.github.com/users/guilhermedeoliveira/following{/other_user}',
    gists_url:
      'https://api.github.com/users/guilhermedeoliveira/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/guilhermedeoliveira/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/guilhermedeoliveira/subscriptions',
    organizations_url: 'https://api.github.com/users/guilhermedeoliveira/orgs',
    repos_url: 'https://api.github.com/users/guilhermedeoliveira/repos',
    events_url:
      'https://api.github.com/users/guilhermedeoliveira/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/guilhermedeoliveira/received_events',
    type: 'User',
    site_admin: false,
    name: 'Guilherme de Brito Oliveira',
    company: '@TallerWebSolutions',
    blog: 'https://www.linkedin.com/in/contatoguilhermedeoliveira',
    location: 'Natal, RN',
    email: null,
    hireable: true,
    bio:
      'Full Stack Developer #javascript #react #reactnative #redux #apollo #graphql #node #docker',
    twitter_username: null,
    public_repos: 55,
    public_gists: 3,
    followers: 11,
    following: 15,
    created_at: '2016-07-02T18:28:17Z',
    updated_at: '2020-05-06T01:16:28Z',
  },
  {
    login: 'Selhar',
    id: 8282304,
    node_id: 'MDQ6VXNlcjgyODIzMDQ=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/8282304?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Selhar',
    html_url: 'https://github.com/Selhar',
    followers_url: 'https://api.github.com/users/Selhar/followers',
    following_url: 'https://api.github.com/users/Selhar/following{/other_user}',
    gists_url: 'https://api.github.com/users/Selhar/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Selhar/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Selhar/subscriptions',
    organizations_url: 'https://api.github.com/users/Selhar/orgs',
    repos_url: 'https://api.github.com/users/Selhar/repos',
    events_url: 'https://api.github.com/users/Selhar/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Selhar/received_events',
    type: 'User',
    site_admin: false,
    name: 'Selhar',
    company: '@TallerWebSolutions',
    blog: 'http://selhar.github.io',
    location: null,
    email: null,
    hireable: true,
    bio: null,
    twitter_username: null,
    public_repos: 40,
    public_gists: 0,
    followers: 51,
    following: 27,
    created_at: '2014-07-27T16:02:09Z',
    updated_at: '2020-05-28T21:29:31Z',
  },
  {
    login: 'rrmontuan',
    id: 6073761,
    node_id: 'MDQ6VXNlcjYwNzM3NjE=',
    avatar_url: 'https://avatars1.githubusercontent.com/u/6073761?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/rrmontuan',
    html_url: 'https://github.com/rrmontuan',
    followers_url: 'https://api.github.com/users/rrmontuan/followers',
    following_url:
      'https://api.github.com/users/rrmontuan/following{/other_user}',
    gists_url: 'https://api.github.com/users/rrmontuan/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/rrmontuan/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/rrmontuan/subscriptions',
    organizations_url: 'https://api.github.com/users/rrmontuan/orgs',
    repos_url: 'https://api.github.com/users/rrmontuan/repos',
    events_url: 'https://api.github.com/users/rrmontuan/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/rrmontuan/received_events',
    type: 'User',
    site_admin: false,
    name: 'Ricardo Montuan',
    company: '@TallerWebSolutions',
    blog: 'https://www.linkedin.com/in/ricardo-montuan',
    location: 'Sao Paulo, Brazil',
    email: null,
    hireable: true,
    bio:
      'Web Developer focused on backend application development, specially using PHP and Yii Framework 2.',
    twitter_username: null,
    public_repos: 12,
    public_gists: 1,
    followers: 11,
    following: 13,
    created_at: '2013-11-30T16:28:23Z',
    updated_at: '2020-05-19T21:01:38Z',
  },
  {
    login: 'delete',
    id: 434694,
    node_id: 'MDQ6VXNlcjQzNDY5NA==',
    avatar_url: 'https://avatars0.githubusercontent.com/u/434694?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/delete',
    html_url: 'https://github.com/delete',
    followers_url: 'https://api.github.com/users/delete/followers',
    following_url: 'https://api.github.com/users/delete/following{/other_user}',
    gists_url: 'https://api.github.com/users/delete/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/delete/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/delete/subscriptions',
    organizations_url: 'https://api.github.com/users/delete/orgs',
    repos_url: 'https://api.github.com/users/delete/repos',
    events_url: 'https://api.github.com/users/delete/events{/privacy}',
    received_events_url: 'https://api.github.com/users/delete/received_events',
    type: 'User',
    site_admin: false,
    name: 'Fellipe Pinheiro',
    company: '@TallerWebSolutions',
    blog: 'fellipe.me',
    location: 'Teresópolis',
    email: null,
    hireable: true,
    bio:
      'Hacking while searching for the answer to Life, the Universe, and Everything.',
    twitter_username: null,
    public_repos: 74,
    public_gists: 20,
    followers: 38,
    following: 52,
    created_at: '2010-10-10T22:33:26Z',
    updated_at: '2020-05-11T14:28:36Z',
  },
  {
    login: 'marcosvlehmkuhl',
    id: 9276461,
    node_id: 'MDQ6VXNlcjkyNzY0NjE=',
    avatar_url: 'https://avatars3.githubusercontent.com/u/9276461?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/marcosvlehmkuhl',
    html_url: 'https://github.com/marcosvlehmkuhl',
    followers_url: 'https://api.github.com/users/marcosvlehmkuhl/followers',
    following_url:
      'https://api.github.com/users/marcosvlehmkuhl/following{/other_user}',
    gists_url: 'https://api.github.com/users/marcosvlehmkuhl/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/marcosvlehmkuhl/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/marcosvlehmkuhl/subscriptions',
    organizations_url: 'https://api.github.com/users/marcosvlehmkuhl/orgs',
    repos_url: 'https://api.github.com/users/marcosvlehmkuhl/repos',
    events_url: 'https://api.github.com/users/marcosvlehmkuhl/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/marcosvlehmkuhl/received_events',
    type: 'User',
    site_admin: false,
    name: null,
    company: null,
    blog: '',
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 8,
    public_gists: 1,
    followers: 21,
    following: 81,
    created_at: '2014-10-17T01:59:46Z',
    updated_at: '2020-06-02T20:05:29Z',
  },
];
